version: "3"

services:
  docdb:
    container_name: docdb
    image: mongo:5.0.3
    ports:
    - "27017:27017"
    networks:
      - internal_network

  ruby:
    container_name: ruby
    working_dir: /app
    build:
      context: .
      dockerfile: ./build/ruby/Dockerfile
    tty: true
    environment:
      DB_HOST: "docdb"
      DB_PORT: 27017
    networks:
      - internal_network

  serverless_framework:
    container_name: serverless_framework
    working_dir: /app
    build:
      context: .
      dockerfile: ./build/serverless_framework/Dockerfile
    tty: true
    volumes:
      - ..:/app/

networks:
  internal_network:
    driver: bridge
