service: nlpf

frameworkVersion: '2'

configValidationMode: error

provider:
  name: aws
  runtime: ruby2.7
  lambdaHashingVersion: 20201221
  timeout: 5
  region: eu-west-3

functions:
  hello:
    handler: lambdas/hello.hello
    events:
      - http:
          path: hello
          method: post

  retrieve_id:
    handler: lambdas/retrieve_id.retrieve_id
    events:
      - http:
          path: id/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
